import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { link } from "fs";
import Image from "next/image";
import NavBar from "./home/navBar/page";
import { BikersPointFooter } from "./footer/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bikers Point",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white antialiased`}
      >
        <NavBar />

        {children}
        <BikersPointFooter />
      </body>
    </html>
  );
}
